#!/bin/sh /etc/rc.common

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

CONFIG=/etc/shadowsocksr.json

start() {
	service_start /usr/bin/ssr-redir -c $CONFIG -b 0.0.0.0
	sleep 1
	service_start /usr/bin/ssr-tunnel -c $CONFIG -b 0.0.0.0 -l 5353 -L 8.8.8.8:53 -u
}

stop() {
	service_stop /usr/bin/ssr-redir
	sleep 1
	service_stop /usr/bin/ssr-tunnel
}
