#!/bin/sh

LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
wget -s -q -T 3 www.google.com.hk
if [ "$?" == "0" ]; then
	echo '['$LOGTIME'] No Problem.'
	exit 0
else
	wget -s -q -T 3 www.baidu.com
	if [ "$?" == "0" ]; then
		echo '['$LOGTIME'] Problem decteted, restarting ShadowsocksR.'
		/etc/init.d/shadowsocksr restart
	else
		echo '['$LOGTIME'] Network Problem. Do nothing.'
	fi
fi
