#!/bin/sh

while true; do
	sleep 60
	
	LOGFILE=/var/log/shadowsocksr_watchdog.log
	LOGSIZE=$(wc -c < $LOGFILE)
	if [ $LOGSIZE -ge 10000 ]; then
		sed -i -e 1,10d $LOGFILE
	fi

	LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")

	wget --spider --quiet -T 3 www.google.com.hk
	if [ "$?" == "0" ]; then
		echo "[$LOGTIME] No problem."
		exit 0
	else
		wget --spider --quiet -T 3 www.baidu.com
		if [ "$?" == "0" ]; then
			echo "[$LOGTIME] Problem decteted, restart ShadowsocksR."
			/etc/init.d/shadowsocksr restart
		else
			echo "[$LOGTIME] Network problem. Do nothing."
		fi
	fi
done
